ai_text_bot/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings # new
from django.conf.urls.static import static # new

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bot/', include('bot.urls')),
    path('engbot/', include('engbot.urls')),
    path('accounts/', include('django.contrib.auth.urls')), # for site authentication
]
#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/bot/validation')),
]

# Use static() to add url mapping to serve static files during development (only)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bot/urls.py
from django.urls import include, path
from . import views

# 用來串接callback主程式
urlpatterns = [
    path('validation/', views.textvalidation, name='text_validation'),
    path('result/', views.result, name='result'),
    path('inquiry/', views.inquiry, name='inquiry'),
    path('line/', views.line, name='line'),
    path('pdf/', views.pdf, name='pdf'),
    path('Alist/', views.textupload_list.as_view(), name='textupload_list'),
    path('Alist/<int:pk>', views.textupload_detail.as_view(), name='textupload_detail'),
    path('Ilist/', views.inquiry_list.as_view(), name='inquiry_list'),
    path('Ilist/<int:pk>', views.inquiry_detail.as_view(), name='inquiry_detail'),
    path('Alistcsv/', views.textupload_csv, name='textupload_csv'),
    path('Ilistcsv/', views.inquiry_csv, name='inquiry_csv'),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

engbot/urls.py
from django.urls import include, path
from . import views

# 用來串接callback主程式
urlpatterns = [
    path('validationEng/', views.textvalidationEng, name='text_validationEng'),
    path('resultEng/', views.resultEng, name='resultEng'),
    path('inquiryEng/', views.inquiryEng, name='inquiryEng'),
    path('lineEng/', views.lineEng, name='lineEng'),
    path('pdfEng/', views.pdfEng, name='pdfEng'),
    path('AlistEng/', views.textupload_listEng.as_view(), name='textupload_listEng'),
    path('AlistEng/<int:pk>', views.textupload_detailEng.as_view(), name='textupload_detailEng'),
    path('IlistEng/', views.inquiry_listEng.as_view(), name='inquiry_listEng'),
    path('IlistEng/<int:pk>', views.inquiry_detailEng.as_view(), name='inquiry_detailEng'),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

engbot/models.py
from django.db import models
from django.urls import reverse
#from django.core.files import File
#import os

class Textuploadeng(models.Model):
    usertext = models.TextField()
    usertext_eng = models.TextField()
    result = models.CharField(max_length=8)
    date_of_upload = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.usertext

    def get_absolute_url(self):
        return reverse('textupload_detailEng', args=[str(self.id)])

class Inquiryeng(models.Model):
    company = models.CharField(max_length=64)
    contact = models.CharField(max_length=16)
    phone = models.CharField(max_length=16)
    fax = models.CharField(max_length=16)
    usertext = models.TextField()
    message = models.TextField()
    date_of_inquiry = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.usertext

    def get_absolute_url(self):
        return reverse('inquiry_detailEng', args=[str(self.id)])

engbot/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

class UploadtextForm(forms.Form):
    usertext = forms.CharField(label="", label_suffix="", initial="",
                                strip=True, min_length=1,
                                widget=forms.Textarea(attrs={'class':'form-control transparent','rows':12, 'cols':14}))

    def clean_usertext(self):
        data = self.cleaned_data['usertext']
        # Check if there is no data.
        if len(data) < 1 :
            raise ValidationError(_("Keyword can't be empty!"))

        # Remember to always return the cleaned data.
        return data

class InquiryForm(forms.Form):
    company = forms.CharField(label="公司名稱", label_suffix="：", initial="",
                                strip=True, min_length=1,
                                widget=forms.Textarea(attrs={'class':'form-control transparent','rows':1, 'cols':8}))
    contact = forms.CharField(label="聯絡人", label_suffix="：", initial="",
                                strip=True, min_length=1,
                                widget=forms.Textarea(attrs={'class':'form-control transparent','rows':1, 'cols':8}))
    phone = forms.CharField(label="電話", label_suffix="：", initial="",
                                strip=True, min_length=1,
                                widget=forms.Textarea(attrs={'class':'form-control transparent','rows':1, 'cols':8}))
    fax = forms.CharField(label="傳真", label_suffix="：", initial="",
                                strip=True, min_length=1,
                                widget=forms.Textarea(attrs={'class':'form-control transparent','rows':1, 'cols':8}))
    usertext = forms.CharField(label="辨識結果", label_suffix="：", initial="",
                                strip=True, min_length=1,
                                widget=forms.Textarea(attrs={'readonly':True,'class':'form-control transparent','rows':6, 'cols':10}))
    message = forms.CharField(label="訊息內容", label_suffix="：", initial="",
                                strip=True, min_length=1,
                                widget=forms.Textarea(attrs={'class':'form-control transparent','rows':6, 'cols':10}))
    #temp string to store keywords
    keywords = forms.CharField(required=True, widget=forms.HiddenInput())


    def clean_company(self):
        data = self.cleaned_data['company']
        return data
    def clean_contact(self):
        data = self.cleaned_data['contact']
        return data
    def clean_phone(self):
        data = self.cleaned_data['phone']
        return data
    def clean_fax(self):
        data = self.cleaned_data['fax']
        return data
    def clean_usertext(self):
        data = self.cleaned_data['usertext']
        return data
    def clean_message(self):
        data = self.cleaned_data['message']
        return data
    def clean_keywords(self):
        data = self.cleaned_data['keywords']
        return data

engbot/views.py
from django.conf import settings
from django.shortcuts import render
from django.http import HttpResponseForbidden, HttpResponse
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from linebot import (LineBotApi, WebhookHandler)
from linebot.exceptions import (InvalidSignatureError)
from linebot.models import (
    TextSendMessage,
)
import os
import time, datetime
from .util import texttool, jieba_validation, trans
from django.views.generic import ListView
#LINE setting
YOUR_CHANNEL_ACCESS_TOKEN = settings.LINE_CHANNEL_ACCESS_TOKEN
YOUR_CHANNEL_SECRET = settings.LINE_CHANNEL_SECRET

line_bot_api = LineBotApi(YOUR_CHANNEL_ACCESS_TOKEN)
handler = WebhookHandler(YOUR_CHANNEL_SECRET)

# upload text
from .models import Textuploadeng
from .forms import UploadtextForm
def textvalidationEng(request):
    form = UploadtextForm()
    content = {
        'form': form,
    }
    return render(request, 'engbot/textvalidationEng.html',content)

#validation result
def resultEng(request):
    if request.method == 'POST':
        form = UploadtextForm(request.POST)
        # Check if the form is valid:
        if form.is_valid():
            text_by_user = form.cleaned_data['usertext']
            date_of_upload = str(datetime.datetime.today())
            #process the text to judge if it is legal
            #result = texttool(text_by_user)
            text_by_user_eng = text_by_user
            text_by_user = trans(text_by_user) # become chinese
            result, rate, keywords = jieba_validation(text_by_user)
            #add red keywords
            #text_by_user_nc = text_by_user
            #r_b = '<span style="color:red;">'
            #r_a = '</span>'
            #for word in keywords:
            #    text_by_user = text_by_user.replace(word, r_b + word + r_a)

            txt = Textuploadeng(usertext=text_by_user, usertext_eng=text_by_user_eng, result=str(result), date_of_upload = date_of_upload)
            txt.save()

            content = {
                'original': txt.usertext_eng,
                'result': txt.result,
                'rate': round(rate * 100, 2),
                'original_nc': text_by_user_eng,
                'keywords': str(keywords).replace("'","").replace(" ",""), #temp string for keywords
            }
            return render(request, 'engbot/resultEng.html', content)

#validation result
from .models import Inquiryeng
from .forms import InquiryForm
from django.utils.safestring import SafeString
def inquiryEng(request):
    if request.method == 'POST':
        result = request.POST.get('result')
        keywords = request.POST.get('keywords')

        form = InquiryForm(initial={'usertext':result, 'keywords': keywords})

        content = {
            'form': form,
        }
        return render(request, 'engbot/inquiryEng.html', content)

#line
def lineEng(request):
    if request.method == 'POST':
        form = InquiryForm(request.POST)
        # Check if the form is valid:
        if form.is_valid():
            company = form.cleaned_data['company']
            contact = form.cleaned_data['contact']
            phone = form.cleaned_data['phone']
            fax= form.cleaned_data['fax']
            usertext = form.cleaned_data['usertext']
            message = form.cleaned_data['message']

            #red words process
            usertext_nc = usertext
            keywords = form.cleaned_data['keywords']
            #keywords = keywords[1:-1].split(',')
            #r_b = '<span style="color:red;">'
            #r_a = '</span>'
            #for word in keywords:
            #    usertext = usertext.replace(word, r_b + word + r_a)
            #red words process end here

            date_of_inquiry = str(datetime.datetime.today())

            inquiry = Inquiryeng(company = company, contact = contact, phone = phone,
                                fax = fax, usertext = usertext, message = message,
                                date_of_inquiry = date_of_inquiry)
            inquiry.save()
            #make message to send by LINE
            LINE = str(contact + " of " + company + " has asked a question.\n\nContent:" + usertext_nc + "\n\nMessage:" + message)
            line_bot_api.broadcast([TextSendMessage(text=LINE)])

        return render(request, 'engbot/lineEng.html')

#pdf generator
from .util import render_to_pdf
def pdfEng(request):
    original = request.POST.get('original')
    result = request.POST.get('result')
    rate = request.POST.get('rate')
    keywords = request.POST.get('keywords')
    #split original
    original = [original[i:i+80] for i in range(0,len(original), 80)]
    #red words process

    if len(keywords) > 2:
        keywords = keywords[1:-1].split(',')
        r_b = '<span style="color:red;">'
        r_a = '</span>'
        for word in keywords:
            for key, value in enumerate(original):
                original[key] = value.replace(word, r_b + word + r_a)

    data = {
        'today': datetime.date.today(),
        'original': original,
        'result': result,
        'rate': rate,
    }
    pdf = render_to_pdf('engbot/pdfEng.html', data)
    return HttpResponse(pdf, content_type='application/pdf')

#####backend site views from here #####
#all_list
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

class textupload_listEng(LoginRequiredMixin, generic.ListView):
    model = Textuploadeng
    paginate_by = 10
    ordering='-date_of_upload'
    template_name = 'engbot/textupload_listEng.html'

#all_detail
class textupload_detailEng(LoginRequiredMixin, generic.DetailView):
    model = Textuploadeng
    template_name = 'engbot/textupload_detailEng.html'

#inquiry_list
class inquiry_listEng(LoginRequiredMixin, generic.ListView):
    model = Inquiryeng
    paginate_by = 10
    ordering='-date_of_inquiry'
    template_name = 'engbot/inquiry_listEng.html'

#inquiry_detail
class inquiry_detailEng(LoginRequiredMixin, generic.DetailView):
    model = Inquiryeng
    template_name = 'engbot/inquiry_detailEng.html'

engbot/templates/engbot/inquiryEng.html
{% extends "base_generic.html" %}
{% block title %}<title>AI Validation</title>{% endblock %}
{% block navbar %}
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'text_validationEng' %}"><i class="fas fa-home fa-lg"></i>Home</a></li>
  </ul>
</div><!-- /.navbar-collapse -->
{% endblock %}
{% block content %}
  <h1 class="logo cursive">Inquiry from website</h1>
  <!--  H1 can have 2 designs: "logo" and "logo cursive"           -->
          <div class="content">
              <div class="subscribe">
                <div class="row">
                  <div class="col-md-4 col-md-offset-4 col-sm6-6 col-sm-offset-3 ">
                      <form action="{% url 'lineEng' %}" method="post" class="form-inline formImg" role="form">
                        <div class="form-group">
                          {% csrf_token %}
                          <!--<table>-->
                          {{form.as_table}}
                          <!--</table>-->
                        </div>
                        <p></p>
                        <button type="submit" class="btn btn-primary btn-fill submitImg">Send Inquiry</button>
                        <br/><br/>
                      </form>
                  </div>
                </div>
              </div>
          </div>

          <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
          <script>
              $(document).ready(function () {
                  $(".formImg").submit(function (e) {
                      //disable the submit button
                      $(".submitImg").attr("disabled", true);
                      return true;
                  });
              });
          </script>

{% endblock %}

engbot/templates/engbot/inquiry_detailEng.html
{% extends "base_generic_db.html" %}
{% block title %}<title>Customer Inquiries</title>{% endblock %}
{% block navbar %}
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#"><i class="far fa-images fa-lg"></i>&nbsp AI Validation Backend Site</a>
  </div>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav navbar-right">
      {% if user.is_authenticated %}
        <!--<li>User: {{ user.get_username }}</li>-->
        <li><a href="{% url 'logout'%}">Logout</a></li>
      {% endif %}
      <li><a href="https://www.openaifab.com" target="_blank"><i class="fas fa-copyright fa-lg"></i>&nbsp 開源智造 Open AI Fab Inc.</a></li>
    </ul>
  </div>
{% endblock %}
{% block sidebar %}
  <ul class="nav nav-sidebar">
    <li><a href="{% url 'textupload_listEng' %}"><i class="fas fa-list fa-lg"></i>&nbsp All Validations</a></li>
    <li class="active"><a href="{% url 'inquiry_listEng' %}"><i class="fas fa-list fa-lg"></i>&nbsp Inquiry List</a></li>
  </ul>
{% endblock %}

{% block content %}
  <h1 class="page-header">Customer Inquiries</h1>
    <div class="row">
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>No</th>
              <th>Date</th>
              <th>Company</th>
              <th>Name</th>
              <th>Phone</th>
              <th>Fax</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>{{inquiryeng.pk}}</td>
              <td>{{inquiryeng.date_of_inquiry}}</td>
              <td>{{inquiryeng.company}}</td>
              <td>{{inquiryeng.contact}}</td>
              <td>{{inquiryeng.phone}}</td>
              <td>{{inquiryeng.fax}}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <div class="row">
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Validation Result</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>{{inquiryeng.usertext|safe}}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <div class="row">
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Message</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>{{inquiryeng.message}}</td>
            </tr>
          </tbody>
        </table>
      </div>
      <p><a href="{% url 'inquiry_listEng' %}">Back to inquiry list</a></p>
    </div>
{% endblock %}

engbot/templates/engbot/inquiry_listEng.html
{% extends "base_generic_db.html" %}
{% block title %}<title>Inquiry List</title>{% endblock %}
{% block navbar %}
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#"><i class="far fa-images fa-lg"></i>&nbsp AI Validation Backend Site</a>
  </div>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav navbar-right">
      {% if user.is_authenticated %}
        <!--<li>User: {{ user.get_username }}</li>-->
        <li><a href="{% url 'logout'%}">Logout</a></li>
      {% endif %}
      <li><a href="https://www.openaifab.com" target="_blank"><i class="fas fa-copyright fa-lg"></i>&nbsp 開源智造 Open AI Fab Inc.</a></li>
    </ul>
  </div>
{% endblock %}
{% block sidebar %}
  <ul class="nav nav-sidebar">
    <li><a href="{% url 'textupload_listEng' %}"><i class="fas fa-list fa-lg"></i>&nbsp All Validations</a></li>
    <li class="active"><a href="#"><i class="fas fa-list fa-lg"></i>&nbsp Inquiry List</a></li>
  </ul>
{% endblock %}

{% block content %}
  <h1 class="page-header">Inquiry List</h1>
    <div class="row">
      {% if inquiryeng_list %}
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>No</th>
              <th>Date</th>
              <th>Company</th>
              <th>Name</th>
              <th>Content</th>
              <th>Message</th>
            </tr>
          </thead>
          <tbody>
          {% for inquiry in inquiryeng_list %}
            <tr>
              <td><a href="{{inquiry.get_absolute_url}}">{{inquiry.pk}}</a></td>
              <td>{{inquiry.date_of_inquiry}}</td>
              <td>{{inquiry.company}}</td>
              <td>{{inquiry.contact}}</td>
              <td>{{inquiry.usertext|slice:"0:15"}} ...</td>
              <td>{{inquiry.message|slice:"0:15"}} ...</td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
      {% else %}
        <p>No vlidation result</p>
      {% endif %}
    </div>
{% endblock %}

engbot/templates/engbot/lineEng.html
{% extends "base_generic.html" %}
{% block title %}<title>AI Validation</title>{% endblock %}
{% block navbar %}
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'text_validationEng' %}"><i class="fas fa-home fa-lg"></i>Home</a></li>
  </ul>
</div><!-- /.navbar-collapse -->
{% endblock %}
{% block content %}
  <h1 class="logo cursive">Your inquiry is sent successfully</h1>
  <!--  H1 can have 2 designs: "logo" and "logo cursive"           -->
{% endblock %}

engbot/templates/engbot/pdfEng.html
<!DOCTYPE HTML>
<html>
    <head>
        <title>Validation Report</title>
        <style type="text/css">
            @font-face {
              font-family: Times;
              /* src: url("/home/r94943024/apps/django/django_projects/ai_text_bot/mingliu.ttc"); */
              src: url("/Users/JeremyLai/django_projects/ai_text_bot/mingliu.ttc");
            }
            body {
                font-weight: 200;
                font-size: 14px;
                font-family: Times;
            }
            .header {
                font-size: 20px;
                font-weight: 100;
                text-align: center;
                color: #007cae;
            }
            .title {
                font-size: 22px;
                font-weight: 100;
               /* text-align: right;*/
               padding: 10px 20px 0px 20px;
            }
            .title span {
                color: #007cae;
            }
            .details {
                padding: 10px 20px 0px 20px;
                text-align: left !important;
                /*margin-left: 40%;*/
            }
            .hrItem {
                border: none;
                height: 1px;
                /* Set the hr color */
                color: #333; /* old IE */
                background-color: #fff; /* Modern Browsers */
            }
        </style>
        <meta charset="UTF-8">
    </head>
    <body>
        <div class='wrapper'>
            <div class='header'>
                <p class='title'>Validation Report</p>
            </div>
        <div>
        <div class='details'>
            Date: {{today}}<br/>
            Advertisement Content:<br/>
            {% for item in original %} {{item|safe}}<br/> {% endfor %}
            <br/>
            {% if result == '0' %}
              Result:  lawful<br/>
            {% elif result == '1' %}
              Result:  unlawful<br/>
            {% endif %}
            Validation result: {{rate}}%<br/>
            <hr class='hrItem' />
            Dear customer：<br/>
            {% if result == '1' %}
              The validation result above is for your reference.<br/>
              「<span style="color:red;">Red light</span>」：The advertisement might be unlawful.<br/>
              「<span style="color:red;">Red text</span>」：The words might be risky.<br/>
            {% endif %}
            <br/>
            Validation result:<br/>
            {% if result == '0' %}
              less than 70%  => 「<span style="color:green;">Congratulation!</span>」Your advertisement might be lawful.<br/>
            {% elif result == '1' %}
              more than 70%  => 「<span style="color:red;">Risky!! </span>」Your advertisement might be unlawful, please be careful.<br/>
            {% endif %}
            <br/>
            If you have further inquiry, please contact us.<br/>
            Phone:(02)23771858 ext:○○○<br/>
            Email: angel.lin@zhongyinlawyer.com.tw<br/>
            <hr class='hrItem' />
        </div>
    </div>
    </body>
</html>

engbot/templates/engbot/textupload_detailEng.html
{% extends "base_generic_db.html" %}
{% block title %}<title>Validation result</title>{% endblock %}
{% block navbar %}
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#"><i class="far fa-images fa-lg"></i>&nbsp AI Validation Backend Site</a>
  </div>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav navbar-right">
      {% if user.is_authenticated %}
        <!--<li>User: {{ user.get_username }}</li>-->
        <li><a href="{% url 'logout'%}">Logout</a></li>
      {% endif %}
      <li><a href="https://www.openaifab.com" target="_blank"><i class="fas fa-copyright fa-lg"></i>&nbsp 開源智造 Open AI Fab Inc.</a></li>
    </ul>
  </div>
{% endblock %}
{% block sidebar %}
  <ul class="nav nav-sidebar">
    <li class="active"><a href="{% url 'textupload_listEng' %}"><i class="fas fa-list fa-lg"></i>&nbsp All Validations</a></li>
    <li><a href="{% url 'inquiry_listEng' %}"><i class="fas fa-list fa-lg"></i>&nbsp Inquiry List</a></li>
  </ul>
{% endblock %}

{% block content %}
  <h1 class="page-header">Validation Result</h1>
    <div class="row">
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>No</th>
              <th>Date</th>
              <th>Result</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>{{textuploadeng.pk}}</td>
              <td>{{textuploadeng.date_of_upload}}</td>
              {% if textuploadeng.result == '0' %}
                <td>Lawful</td>
              {% else %}
                <td>Unlawful</td>
              {% endif %}
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <div class="row">
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Content</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>{{textuploadeng.usertext_eng|safe}}</td>
            </tr>
          </tbody>
        </table>
      </div>
      <p><a href="{% url 'textupload_listEng' %}">Back to list</a></p>
    </div>
{% endblock %}

engbot/templates/engbot/textupload_listEng.html
{% extends "base_generic_db.html" %}
{% block title %}<title>All validation result</title>{% endblock %}
{% block navbar %}
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#"><i class="far fa-images fa-lg"></i>&nbsp AI Validation Backend Site</a>
  </div>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav navbar-right">
      {% if user.is_authenticated %}
        <!--<li>User: {{ user.get_username }}</li>-->
        <li><a href="{% url 'logout'%}">Logout</a></li>
      {% endif %}
      <li><a href="https://www.openaifab.com" target="_blank"><i class="fas fa-copyright fa-lg"></i>&nbsp 開源智造 Open AI Fab Inc.</a></li>
    </ul>
  </div>
{% endblock %}
{% block sidebar %}
  <ul class="nav nav-sidebar">
    <li class="active"><a href="#"><i class="fas fa-list fa-lg"></i>&nbsp All Validations</a></li>
    <li><a href="{% url 'inquiry_listEng' %}"><i class="fas fa-list fa-lg"></i>&nbsp Inquiry List</a></li>
  </ul>
{% endblock %}

{% block content %}
  <h1 class="page-header">All Validations</h1>
    <div class="row">
      {% if textuploadeng_list %}
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>No</th>
              <th>Date</th>
              <th>Content</th>
              <th>Result</th>
            </tr>
          </thead>
          <tbody>
          {% for textupload in textuploadeng_list %}
            <tr>
              <td><a href="{{textupload.get_absolute_url}}">{{textupload.pk}}</a></td>
              <td>{{textupload.date_of_upload}}</td>
              <td>{{textupload.usertext_eng|slice:"0:40"}} ...</td>
              {% if textupload.result == '0' %}
                <td>Lawful</td>
              {% else %}
                <td>unlawful</td>
              {% endif %}
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
      {% else %}
        <p>No validation result</p>
      {% endif %}
    </div>
{% endblock %}